version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
  #   volumes:
  #     - ./src/webrtcTest:/var/www
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php

  # php:
  #   build: ./docker/php
  #   container_name: php
  #   volumes:
  #     - ./src/webrtcTest:/var/www


  # db:
  #   image: mysql:5.7
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: sample_project
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - ./docker/db/data:/var/lib/mysql
  #     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./docker/db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3306:3306

  # node:
  #   image: node:12.13-alpine
  #   container_name: node
  #   tty: true
  #   volumes:
  #     - ./src/webrtcTest:/var/www
  #   working_dir: /var/www