version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./source:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: ./php-fpm
    container_name: php
    volumes:
      - ./source:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webrtc_test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  # node:
  #   image: node:12.13-alpine
  #   container_name: node
  #   tty: true
  #   volumes:
  #     - ./src/webrtcTest:/var/www
  #   working_dir: /var/www